version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -ppassword"
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 10s
    container_name: graphql_db

  # graphql_1.12_ruby_2.7
  app1:
    build: ./graphql_1.12_ruby_2.7/.
#    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails db:seed:replant && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./graphql_1.12_ruby_2.7:/myapp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development 
    container_name: graphql_app1

  # graphql_2.2_ruby_2.7
  app2:
    build: ./graphql_2.2_ruby_2.7/.
#    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails db:seed:replant && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./graphql_2.2_ruby_2.7:/myapp
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development 
    container_name: graphql_app2

  # graphql_2.2_ruby_3.1
  app3:
    build: ./graphql_2.2_ruby_3.1/.
#    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails db:seed:replant && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./graphql_2.2_ruby_3.1:/myapp
    ports:
      - "3002:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development 
    container_name: graphql_app3

  app4:
    build:
      context: ./rest_ruby_3.1
      dockerfile: Dockerfile
#    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails db:seed:replant && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./rest_ruby_3.1:/myapp
    ports:
      - "3003:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development 
    container_name: graphql_app4

volumes:
  db-store: